extends Node3D
# All samples are original, generated by tools/generate_sounds.py.
const BUS := "SimulatorEffects"
var sim: Node3D
var samples: Dictionary = {}
var loops: Dictionary = {}
var previous: Dictionary = {}
var run_id := ""
var effects_played := 0
var initialized := false
var enabled := true
var gain := .65
var recent_order_ms := -1000


func _ready() -> void:
	if AudioServer.get_bus_index(BUS) < 0:
		AudioServer.add_bus()
		AudioServer.set_bus_name(AudioServer.bus_count - 1, BUS)
	for key in ["rotor", "kitchen", "packing", "order", "pickup", "delivered"]:
		var stream := AudioStreamWAV.load_from_file("res://audio/" + key + ".wav")
		if key in ["rotor", "kitchen"]:
			stream.loop_mode = AudioStreamWAV.LOOP_FORWARD
			stream.loop_end = stream.data.size() / 2
		samples[key] = stream


func apply_config(config: Dictionary) -> void:
	enabled = config.get("sfx_enabled", true)
	gain = float(config.get("sfx_volume", .65))
	var bus := AudioServer.get_bus_index(BUS)
	AudioServer.set_bus_mute(bus, not enabled or gain <= 0)
	AudioServer.set_bus_volume_db(bus, linear_to_db(maxf(.001, gain)))
	if not enabled or gain <= 0:
		for child in get_children():
			if child.has_meta("oneshot"):
				child.queue_free()


func play_effect(
	key: String, point: Vector3, global_notice := false, allow_on_title := false
) -> void:
	if not enabled or gain <= 0 or (sim.ui.title_visible and not allow_on_title):
		return
	var count := 0
	for child in get_children():
		if child.has_meta("oneshot"):
			count += 1
	if count >= 8:
		return
	var player: Node
	if global_notice:
		player = AudioStreamPlayer.new()
	else:
		player = AudioStreamPlayer3D.new()
		player.max_distance = 65
		player.unit_size = 8
	player.bus = BUS
	player.stream = samples[key]
	player.volume_db = -12.0
	player.set_meta("oneshot", true)
	add_child(player)
	if player is Node3D:
		player.global_position = point
	player.finished.connect(player.queue_free)
	player.play()
	effects_played += 1


func observe(state: Dictionary) -> void:
	apply_config(state.config)
	var fresh_run: String = state.run_id
	if not initialized or fresh_run != run_id:
		initialized = true
		run_id = fresh_run
		previous.clear()
		for child in get_children():
			child.queue_free()
		loops.clear()
		for job in state.orders:
			previous[int(job.id)] = job.state
		return
	for job in state.orders:
		var id := int(job.id)
		var before: String = previous.get(id, "")
		if before == job.state:
			continue
		previous[id] = job.state
		var point := Vector3.ZERO
		if int(job.cafe) < sim.cafes.size():
			point = sim.cafes[int(job.cafe)].node.global_position + Vector3.UP * 1.8
		if before.is_empty():
			# One notice per burst, even if 200 customers order together.
			if Time.get_ticks_msec() - recent_order_ms > 350:
				play_effect("order", point, true)
				recent_order_ms = Time.get_ticks_msec()
		elif state.running:
			if job.state == "PACKING":
				play_effect("packing", point)
			elif job.state == "OUT FOR DELIVERY":
				play_effect("pickup", point)
			elif job.state == "DELIVERED":
				if int(job.human) < sim.humans.size():
					point = sim.humans[int(job.human)].node.global_position
				play_effect("delivered", point)


func update_loop(key: String, sample: String, point: Vector3, active: bool, pitch: float) -> void:
	if not loops.has(key):
		if not active:
			return
		var player := AudioStreamPlayer3D.new()
		player.stream = samples[sample]
		player.bus = BUS
		player.unit_size = 6
		player.max_distance = 65
		player.volume_db = -20 if sample == "rotor" else -14
		add_child(player)
		loops[key] = player
	var sound: AudioStreamPlayer3D = loops[key]
	sound.global_position = point
	sound.pitch_scale = pitch
	if active and not sound.playing:
		sound.play()
	elif not active and sound.playing:
		sound.stop()


func _process(_delta: float) -> void:
	var audible: bool = (
		enabled
		and gain > 0
		and sim.running
		and not sim.ui.title_visible
		and sim.transport.connected()
	)
	for i in sim.vehicles.size():
		var drone: Dictionary = sim.vehicles[i]
		var speed := 0.0
		if i < sim.state.get("vehicles", []).size():
			var velocity: Array = sim.state.vehicles[i].velocity
			speed = Vector3(velocity[0], velocity[1], velocity[2]).length()
		update_loop(
			"drone-%d" % i,
			"rotor",
			drone.node.global_position,
			audible and drone.state not in ["IDLE", "CHARGING", "DIAGNOSING", "REPAIRING"],
			.85 + minf(speed, 12) / 30
		)
	for i in sim.docks.size():
		update_loop(
			"repair-%d" % i,
			"kitchen",
			sim.docks[i].node.global_position,
			audible and sim.vehicles[i].state == "REPAIRING",
			.75
		)
	for i in sim.cafes.size():
		var cafe: Dictionary = sim.cafes[i]
		var working: bool = (
			cafe.job >= 0
			and cafe.job < sim.orders.size()
			and sim.orders[cafe.job].state in ["COOKING", "PACKING", "SHIPPING"]
		)
		update_loop("cafe-%d" % i, "kitchen", cafe.node.global_position, audible and working, 1.0)
	for child in get_children():
		if child.has_meta("oneshot"):
			child.stream_paused = not sim.running or not sim.transport.connected()
